<a href="https://colab.research.google.com/github/restlessbear82/pln_unal/blob/main/Cuaderno_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Procesamiento de Lenguaje Natural**

**Cuaderno de implementación de la librería Numpy de Python**

Gustavo Adolfo García Vélez - 80115870

In [27]:
#Importación de la librería
import numpy as np

In [28]:
#Creación básica de arrays
#El número de dimensiones viene dado por el número de paréntesis cuadrados
a = np.array(6) #array de dimensión 0
b = np.array([1,2,3,4]) #array de dimensión 1
c = np.array([[1,2,3,4],[5,6,7,8]]) #array de dimensión 2
d = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #array de dimensión 3
e = np.array([[[1,2],[3,4],[5,6]]]) #array de dimensión 3
f = np.array([[[[1,2,3,4],[4,3,2,1]]]]) #array de dimensión 4

print("a =",a,"\n")
print("b =",b,"\n")
print("c =",c,"\n")
print("d =",d,"\n")
print("e =",e,"\n")
print("f =",f,"\n")

a = 6 

b = [1 2 3 4] 

c = [[1 2 3 4]
 [5 6 7 8]] 

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

e = [[[1 2]
  [3 4]
  [5 6]]] 

f = [[[[1 2 3 4]
   [4 3 2 1]]]] 



In [29]:
#verificación de la dimensionalidad de los arrays con la instrucción ndim

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)

0
1
2
3
3
4


In [30]:
#Indexación básica en el array. 
#La indexación busca el elemento de la dimensión correspondiente. 

#Búsqueda en la  primera dimensión

print("a =", a)
print("b[1] =", b[1])
print("c[2] =", c[1])
print("f[1] =", f[0])

a = 6
b[1] = 2
c[2] = [5 6 7 8]
f[1] = [[[1 2 3 4]
  [4 3 2 1]]]


In [31]:
#Búsqueda en la segunda dimensión

print("a =",a)
print("b[2] =",b[2])
print("c[1,2] =",c[1,2])
print("f[0,1,2] =",f[0,0,1])

a = 6
b[2] = 3
c[1,2] = 7
f[0,1,2] = [4 3 2 1]


In [32]:
#Segmentación de arrays
print(b[1:4]) #b = [1 2 3 4] 
print(c[1,1:3]) #c = [[1 2 3 4][5 6 7 8]] 

[2 3 4]
[6 7]


In [33]:
#Otros tipos de datos en los arrays

#Array de tipo cadena de dimensión cero
verduras = np.array(['Espinaca','Apio','Lechuga','Auyama'])

#Array de tipo booleano de dimensión 2
verdad = np.array([[True,False],[False,True]])

#Array de punto flotante
trascendentes = np.array([3.1416,2.7129])

print(verduras.dtype)
print(verdad.dtype)
print(trascendentes.dtype)

<U8
bool
float64


In [34]:
#Conversión de tipos de datos
#tipo integer a string

number_to_string=np.array(b, dtype='S') 
print(number_to_string.dtype)
print(number_to_string)

#tipo punto flotante a string

float_to_string=np.array(trascendentes, dtype='S') 
print(float_to_string.dtype)
print(float_to_string)

|S21
[b'1' b'2' b'3' b'4']
|S32
[b'3.1416' b'2.7129']


In [35]:
#Excepción que muestra un error de creación de un array. 

try:
    error_array = np.array([False, '2', '3'], dtype='i')
except:
    print("hay un error en su lógica. El array contiene diferentes tipos de datos")

In [36]:
#Cambio de tipo en arrays ya existentes, siempre y cuando el cambio sea posible

float_array = np.array([1.0, 2.1, 3.2])
int_array = float_array.astype('b')
print(int_array)

[1 2 3]


In [37]:
#Forma de los arrays. Se define como el número de elementos de cada dimensión.

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)
print(f.shape)

()
(4,)
(2, 4)
(2, 2, 4)
(1, 3, 2)
(1, 1, 2, 4)


In [38]:
#Cambio de forma de los arrays, aumentando el número de dimensiones o cambiando el número de elementos por dimensión.  
#Es posible realizar cualquier cambio en la forma, siempre y cuando el número final de elementos sea el mismo.

print("f =",f,"\n")
f_1D=f.reshape(1,8)
print("c_1D =",f_1D,"\n")
f_4D=f.reshape(4,2)
print("c_4D =",f_4D,"\n")

f = [[[[1 2 3 4]
   [4 3 2 1]]]] 

c_1D = [[1 2 3 4 4 3 2 1]] 

c_4D = [[1 2]
 [3 4]
 [4 3]
 [2 1]] 



In [39]:
#Cambios de forma que no son posibles
print(d)
print(d.shape)
try:
    d.reshape(3,5)
except:
    print('Hay un error en sus operaciones')

d.reshape(2,4,2)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
(2, 2, 4)
Hay un error en sus operaciones


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [40]:
#Ajuste automático de dimensiones ("Dimensión desconocida")
#El ajuste automático funciona, siempre y cuando el número de dimensiones sea divisor del número de elementos

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr.reshape(5,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [41]:
#Aplanamiento de dimensiones. 
f.reshape(-1)

array([1, 2, 3, 4, 4, 3, 2, 1])

In [42]:
#Transpuesta de un array
print("c =",c)
print(c.shape,"\n")
print("c.T =",c.T)
print(c.T.shape)

c = [[1 2 3 4]
 [5 6 7 8]]
(2, 4) 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]
(4, 2)


In [43]:
#Iteración de arrays. Con un bucle 'for' se muestra cada dimensión del array con sus elementos respectivos
for x in f:
    print(x)

[[[1 2 3 4]
  [4 3 2 1]]]


In [44]:
#Recorrido del array con bucles for, en cada dimensión (se hace para un array de 4 dimensiones)
for x in f:
    for y in x:
        for z in y:
          for w in z:
            print(w)

1
2
3
4
4
3
2
1


In [45]:
#El mismo resultado anterior se consigue con la función nditer

for x in np.nditer(f):
    print(x)

1
2
3
4
4
3
2
1


In [46]:
#Operaciones entre arrays

#Suma con np.add (aplica entre argumentos, dando como resultado un array de la misma forma):
#para la suma, los arrays deben tener la misma forma

arr1 = np.array([[6,5,4],
               [3,2,1]])
arr2 = np.array([[5,6,7],
               [8,9,10]])
np.add(arr1, arr2)


array([[11, 11, 11],
       [11, 11, 11]])

In [47]:
#Suma con np.sum
#En esta suma, el resultado es la adición de todos los elementos de los arrays presentes

arr3 = np.array([[1,1,1],[1,1,1]])

print(np.sum([arr1, arr2]))
print(np.sum([arr1, arr2, arr3]))

66
72


In [48]:
#Al aplicar la función np.sum a un eje específico, no se obtiene un escalar sino un nuevo array de la misma forma de los anteriores

arr4 = np.sum([arr1, arr2, arr3], axis=0) #Da el mismo resultado que np.add
print(arr4)
arr5 = np.add(arr1, arr2, arr3)
print(arr5)
arr6 = np.sum([arr1, arr2, arr3], axis=1)
print(arr6)

[[12 12 12]
 [12 12 12]]
[[11 11 11]
 [11 11 11]]
[[ 9  7  5]
 [13 15 17]
 [22 22 22]]


In [49]:
#Multiplicación de todos los elementos de los arrays
#un array se puede multiplicar por sí mismo o por otro array de la misma forma para obtener, o bien un número
#o bien otro array (si se hace la multiplicación por ejes)

print("arr1 =\n",arr1,"\n")
print("arr2 =\n",arr2,"\n")
print(np.prod([arr1, arr2]),"\n") #Producto de arr1 y arr2
print(np.prod([arr1, arr2],axis = 0),"\n") #Producto de arr1 y arr2, eje 0
print(np.prod([arr1, arr2],axis = 1)) #Producto de arr1 y arr2, eje 1

arr1 =
 [[6 5 4]
 [3 2 1]] 

arr2 =
 [[ 5  6  7]
 [ 8  9 10]] 

108864000 

[[30 30 28]
 [24 18 10]] 

[[18 10  4]
 [40 54 70]]


In [51]:
#Multiplicación matricial

#Función matmul. Ejecuta una multiplicación entre matrices, siguiendo las reglas aprendidas en álgebra lineal
print(arr1)
print(arr2)
np.matmul(arr1, arr2.T)

[[6 5 4]
 [3 2 1]]
[[ 5  6  7]
 [ 8  9 10]]


array([[ 88, 133],
       [ 34,  52]])

In [52]:
#Función dot para multiplicar matrices
np.dot(arr1, arr2.T)

array([[ 88, 133],
       [ 34,  52]])

In [53]:
#Multiplicación elemento a elemento de los arrays con np.dot

print("d =\n",d,"\n") #2,2,4
print("d.reshape =\n",d.reshape(2,4,2),"\n") #2,4,2
np.dot(d,d.reshape(2,4,2)) #2,2,2,2

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.reshape =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] 



array([[[[ 50,  60],
         [130, 140]],

        [[114, 140],
         [322, 348]]],


       [[[178, 220],
         [514, 556]],

        [[242, 300],
         [706, 764]]]])

In [54]:
#Multiplicación de elementos particulares de los arrays con np.dot

print(np.dot(d[0],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[0],d.reshape(2,4,2)[1]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[1]),"\n")

[[ 50  60]
 [114 140]] 

[[130 140]
 [322 348]] 

[[178 220]
 [242 300]] 

[[514 556]
 [706 764]] 



In [55]:
#Multiplicación de arrays con np.matmul
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])